### ISSUE TITLE
Author name on home and post is not shown properly on Skeleton

### ISSUE THREAD

**Issue by AbrahamAriel** [dignajar/bludit-themes#20]
The code is done to make sure that it shows the name(s) if available, else revert to the username. However it was done wrong. It keeps using the username regardless.

To fix this, change && to || in this line:
`
if( Text::isNotEmpty($Post->authorFirstName()) && Text::isNotEmpty($Post->authorLastName()) )
`

Fixed:
`
if( Text::isNotEmpty($Post->authorFirstName()) || Text::isNotEmpty($Post->authorLastName()) )
`

**Comment by dignajar** [comment]
authorFirstName and authorLastName are depreacted. Sorry for my late answer, I recently update the themes.
