### ISSUE TITLE
Menu button on theme Future Imperfect not being displayed

### ISSUE THREAD

**Issue by hulbs** [dignajar/bludit-themes#21]
Can be seen at http://ihackpotplants.com .
I have changed a some of the colours and modified a couple of plugins along with a few other bits and bobs but even a full theme restore didn't fix it.

**Comment by hulbs** [comment]
So yeh got the name wrong...

**Comment by dignajar** [comment]
I fixed this, the theme is in Github https://github.com/dignajar/bludit/tree/master/bl-themes
